
- connection: local
  hosts: localhost
  tasks:
    - import_role:
        name: basic
      tags:
        - basic
    - import_role:
        name: fish
      tags:
        - fish
    - import_role:
        name: spacemacs
      tags:
        - spacemacs
    - import_role:
        name: clojure
      tags:
        - clojure
    - import_role:
        name: haskell
      tags:
        - haskell
