
- connection: local
  hosts: localhost
  tasks:
    - import_role:
        name: basic
      tags:
        - basic
    - import_role:
        name: git
      tags:
        - git
    - import_role:
        name: fish
      tags:
        - fish
    - import_role:
        name: gpg
      tags:
        - gpg
    - import_role:
        name: doom
      tags:
        - doom
    - import_role:
        name: clojure
      tags:
        - clojure
    - import_role:
        name: alacritty
      tags:
        - alacritty
    - import_role:
        name: qutebrowser
      tags:
        - qutebrowser
    - import_role:
        name: stumpwm
      tags:
        - stumpwm
