
- connection: local
  hosts: localhost
  tasks:
    - name: install packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - emacs
        - neovim
        - git
        - fish
        - tmux
        - powerline
        - fonts-powerline
        - silversearcher-ag
        - curl
    - name: checkout spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.emacs.d
    - file:
        path: ~/.config/fish
        state: directory
    - name: fish config
      template:
        src: config.fish.j2
        dest: ~/.config/fish/config.fish
    - file:
        path: ~/.local/bin
        state: directory
    - name: tmux config
      template:
        src: tmux.conf.j2
        dest: ~/.tmux.conf

