- connection: local
  hosts: localhost
  vars:
    packages_to_install:
        - gnome-tweaks
        - emacs
        - neovim
        - git
        - fish
        - tilix
        - powerline
        - the_silver_searcher
        - curl
        - glances
        - docker
        - python3-docker
        - chromium
        - "@multimedia"
  tasks:
    - name: install packages
      become: yes
      dnf:
        name: "{{ packages_to_install }}"
        state: present
    - name: checkout spacemacs
      git:
        repo: https://github.com/syl20bnr/spacemacs
        dest: ~/.emacs.d
    - name: spacemacs config
      template:
        src: spacemacs.j2
        dest: ~/.spacemacs
    - file:
        path: ~/.config/fish
        state: directory
    - name: fish config
      template:
        src: config.fish.j2
        dest: ~/.config/fish/config.fish
    - file:
        path: ~/.local/bin
        state: directory
