
- name: create local bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: download lein
  get_url:
    url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    dest: ~/.local/bin/lein
    mode: "a+x"
