
- name: install packages
  become: yes
  apt:
    name: "{{ packages_to_install }}"
    state: present

- name: checkout doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
    version: develop
    update: no

- name: create doom directory
  file:
    path: ~/.doom.d
    state: directory

- name: update doom emacs configs
  template:
    src: "{{ item }}"
    dest: "~/.doom.d/{{ item }}"
  loop:
    - config.el
    - init.el
    - packages.el

- name: create systemd user directory
  file:
    path: ~/.config/systemd/user
    state: directory

- name: create emacs systemd service
  template:
    src: emacs.service.j2
    dest: "~/.config/systemd/user/emacs.service"

- name: enable emacs service
  systemd:
    scope: user
    name: emacs
    enabled: true

