
- name: create local tmp directory
  file:
    path: ~/.local/tmp
    state: directory

- name: create local bin directory
  file:
    path: ~/.local/bin
    state: directory

- name: install prereq packages
  become: yes
  dnf:
    name: "{{ packages_to_install }}"
    state: present

- name: download stack
  get_url:
    url: https://get.haskellstack.org/stable/linux-x86_64-static.tar.gz
    dest: ~/.local/tmp/linux-x86_64-static.tar.gz

- name: unarchive stack
  unarchive:
    src: ~/.local/tmp/linux-x86_64-static.tar.gz
    dest: ~/.local/tmp

- name: copy stack to bin directory
  shell: cp ~/.local/tmp/stack-*-linux-x86_64-static/stack ~/.local/bin/stack
  args:
    creates: ~/.local/bin/stack
