
- name: enable alacritty ppa
  become: yes
  apt_repository:
    repo: ppa:mmstick76/alacritty
    state: present
  register: ala_ppa_out

- name: update apt
  become: yes
  apt:
    update_cache: yes
  when: ala_ppa_out is changed

- name: install alacritty
  become: yes
  apt:
    name: alacritty
    state: present
